add_newline = false

[conda]
format = '[$symbol$environment](bold green) '
ignore_base = true



[git_status]
ahead = "[⇡${count}](green)"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
modified = "!${count}"
untracked = "?${count}"
staged = '[++$count](green)'
conflicted = "=${count}"
stashed = '\$${count}'
# format = '([$all_status$ahead_behind]($style) )'





