vim.keymap.set("i", "<A-m>", function() return vim.fn["codeium#Accept"]() end, { expr = true }, {desc = "Accept AI code"})
vim.keymap.set("i", "<A-j>", function() return vim.fn["codeium#CycleCompletions"](1) end, { expr = true }, {desc= "Next AI code suggestion"})
vim.keymap.set("i", "<A-k>", function() return vim.fn["codeium#CycleCompletions"](-1) end, { expr = true }, {desc= "Previous AI code suggestion"})
vim.keymap.set("i", "<A-x>", function() return vim.fn["codeium#Clear"]() end, { expr = true }, {desc = "Clear AI code suggestions"})
vim.keymap.set("i", "<A-s>", function() return vim.fn["codeium#Complete"]() end, { expr = true }, {desc = "AI code: Complete (?)"})
